use std::sync::Arc;
use axum::{extract::{Path, Query, State}, http::StatusCode, response::IntoResponse, Json};
use chrono::Utc;
use uuid::Uuid;
use rzops_domain::enums::{MonitorType, ReservedStatus};
use rzops_domain::models::monitor_target::MonitorTarget;
use rzops_domain::ports::monitor_target_repository::{MonitorTargetFilter, MonitorTargetRepository};
use crate::dto::provider_dto::ErrorResponse;
use crate::dto::monitor_target_dto::*;
use crate::auth_extractor::AuthUser;

fn parse_mt(s:&str)->MonitorType{match s{"ping"=>MonitorType::Ping,"http"=>MonitorType::Http,"tcp"=>MonitorType::Tcp,"tls"=>MonitorType::Tls,_=>MonitorType::Custom}}
fn mt_to_string(t:&MonitorType)->String{match t{MonitorType::Ping=>"ping",MonitorType::Http=>"http",MonitorType::Tcp=>"tcp",MonitorType::Tls=>"tls",MonitorType::Custom=>"custom"}.to_string()}
fn parse_status(s:&str)->ReservedStatus{match s{"draft"=>ReservedStatus::Draft,"active"=>ReservedStatus::Active,"inactive"=>ReservedStatus::Inactive,"archived"=>ReservedStatus::Archived,_=>ReservedStatus::Draft}}
fn status_to_string(s:&ReservedStatus)->String{match s{ReservedStatus::Draft=>"draft",ReservedStatus::Active=>"active",ReservedStatus::Inactive=>"inactive",ReservedStatus::Archived=>"archived"}.to_string()}
fn to_resp(e:&MonitorTarget)->MonitorTargetResponse{MonitorTargetResponse{id:e.id,name:e.name.clone(),target_type:e.target_type.clone(),target_id:e.target_id,monitor_type:e.monitor_type.as_ref().map(mt_to_string),endpoint:e.endpoint.clone(),interval_seconds:e.interval_seconds,status:status_to_string(&e.status),remarks:e.remarks.clone(),created_at:e.created_at,updated_at:e.updated_at}}

#[utoipa::path(get, path = "/api/v1/monitor-targets/{id}", params(("id" = uuid::Uuid, Path)), responses((status = 200, body = MonitorTargetResponse), (status = 404, body = ErrorResponse)), tag = "MonitorTargets", security(("bearer_auth" = [])))]
pub async fn get_monitor_target(_auth: AuthUser, State(r):State<Arc<dyn MonitorTargetRepository>>,Path(id):Path<Uuid>)->impl IntoResponse{match r.find_by_id(id).await{Ok(Some(e))=>(StatusCode::OK,Json(to_resp(&e))).into_response(),Ok(None)=>(StatusCode::NOT_FOUND,Json(ErrorResponse{error:"not found".into()})).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(ErrorResponse{error:e.to_string()})).into_response()}}
#[utoipa::path(get, path = "/api/v1/monitor-targets", params(ListMonitorTargetsQuery), responses((status = 200, body = MonitorTargetListResponse)), tag = "MonitorTargets", security(("bearer_auth" = [])))]
pub async fn list_monitor_targets(_auth: AuthUser, State(r):State<Arc<dyn MonitorTargetRepository>>,Query(q):Query<ListMonitorTargetsQuery>)->impl IntoResponse{let p=q.page.unwrap_or(1).max(1);let pp=q.per_page.unwrap_or(20).min(100);let f=MonitorTargetFilter{status:q.status,q:q.q,limit:Some(pp),offset:Some((p-1)*pp)};match r.find_all(f.clone()).await{Ok(v)=>{let c=r.count(f).await.unwrap_or(0);(StatusCode::OK,Json(MonitorTargetListResponse{data:v.iter().map(to_resp).collect(),count:c})).into_response()},Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(ErrorResponse{error:e.to_string()})).into_response()}}
#[utoipa::path(post, path = "/api/v1/monitor-targets", request_body = CreateMonitorTargetRequest, responses((status = 201, body = MonitorTargetResponse), (status = 400, body = ErrorResponse)), tag = "MonitorTargets", security(("bearer_auth" = [])))]
pub async fn create_monitor_target(_auth: AuthUser, State(r):State<Arc<dyn MonitorTargetRepository>>,Json(b):Json<CreateMonitorTargetRequest>)->impl IntoResponse{let now=Utc::now();let e=MonitorTarget{id:Uuid::new_v4(),name:b.name,target_type:b.target_type,target_id:b.target_id,monitor_type:b.monitor_type.as_deref().map(parse_mt),endpoint:b.endpoint,interval_seconds:b.interval_seconds,status:b.status.as_deref().map(parse_status).unwrap_or(ReservedStatus::Draft),remarks:b.remarks,created_at:now,updated_at:now};match r.create(&e).await{Ok(c)=>(StatusCode::CREATED,Json(to_resp(&c))).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(ErrorResponse{error:e.to_string()})).into_response()}}
#[utoipa::path(put, path = "/api/v1/monitor-targets/{id}", params(("id" = uuid::Uuid, Path)), request_body = UpdateMonitorTargetRequest, responses((status = 200, body = MonitorTargetResponse), (status = 404, body = ErrorResponse)), tag = "MonitorTargets", security(("bearer_auth" = [])))]
pub async fn update_monitor_target(_auth: AuthUser, State(r):State<Arc<dyn MonitorTargetRepository>>,Path(id):Path<Uuid>,Json(b):Json<UpdateMonitorTargetRequest>)->impl IntoResponse{let ex=match r.find_by_id(id).await{Ok(Some(e))=>e,Ok(None)=>return(StatusCode::NOT_FOUND,Json(ErrorResponse{error:"not found".into()})).into_response(),Err(e)=>return(StatusCode::INTERNAL_SERVER_ERROR,Json(ErrorResponse{error:e.to_string()})).into_response()};let e=MonitorTarget{id:ex.id,name:b.name.unwrap_or(ex.name),target_type:b.target_type.or(ex.target_type),target_id:b.target_id.or(ex.target_id),monitor_type:b.monitor_type.as_deref().map(parse_mt).or(ex.monitor_type),endpoint:b.endpoint.or(ex.endpoint),interval_seconds:b.interval_seconds.or(ex.interval_seconds),status:b.status.as_deref().map(parse_status).unwrap_or(ex.status),remarks:b.remarks.or(ex.remarks),created_at:ex.created_at,updated_at:Utc::now()};match r.update(id,&e).await{Ok(Some(c))=>(StatusCode::OK,Json(to_resp(&c))).into_response(),Ok(None)=>(StatusCode::NOT_FOUND,Json(ErrorResponse{error:"not found".into()})).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(ErrorResponse{error:e.to_string()})).into_response()}}
#[utoipa::path(delete, path = "/api/v1/monitor-targets/{id}", params(("id" = uuid::Uuid, Path)), responses((status = 200), (status = 404, body = ErrorResponse)), tag = "MonitorTargets", security(("bearer_auth" = [])))]
pub async fn delete_monitor_target(_auth: AuthUser, State(r):State<Arc<dyn MonitorTargetRepository>>,Path(id):Path<Uuid>)->impl IntoResponse{match r.delete(id).await{Ok(true)=>StatusCode::NO_CONTENT.into_response(),Ok(false)=>(StatusCode::NOT_FOUND,Json(ErrorResponse{error:"not found".into()})).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(ErrorResponse{error:e.to_string()})).into_response()}}
